services:
  # Banco de dados PostgreSQL
  
  # Backend API
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/projeto_ecommerce
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ecommerce-network
    volumes:
      - ../backend:/app
      - /app/node_modules
    develop:
      watch:
        - action: sync
          path: ../backend/src
          target: /app/src
        - action: rebuild
          path: ../backend/package.json

  # Frontend React
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:3001
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - ecommerce-network
    volumes:
      - ../frontend:/app
      - /app/node_modules
    develop:
      watch:
        - action: sync
          path: ../frontend/src
          target: /app/src
        - action: rebuild
          path: ../frontend/package.json


networks:
  ecommerce-network:
    driver: bridge